name: Run tests and upload coverage

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Node.js dependencies
        run: npm install

      - name: Verify Jest installation
        run: ls -l ./node_modules/.bin/jest

      - name: Run Node.js tests
        run: |
          chmod +x ./node_modules/.bin/jest
          ./node_modules/.bin/jest --coverage --passWithNoTests

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run Python script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: python bucket_co.py

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: |
            coverage/lcov.info  # Node.js Jest coverage
            coverage-python.xml  # Python coverage XML
          fail_ci_if_error: true
